version: '3.5'
services:
    api:
        image: ranger.services.projects:dev
        container_name: projects
        ports:
            - '8086:8086'
        networks:
            - ranger

networks:
    ranger:
        name: ranger-network
        external: true
