version: '3.5'
services:
    postgres:
        image: postgres:9.6
        container_name: projects_postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        networks:
            - projects
        volumes:
            - postgres:/data/db

networks:
    projects:
        name: projects-network
        internal: true

volumes:
    postgres:
        driver: local
